#!/usr/bin/env bash
# creat script that uses the if, elif, while and else statements
# on the 4 print bad luck ,on 8 print good luck , otherwise print best school
i=0;
while [ $i -le 9 ];
do
if [ $i == 3 ]
then 
echo "bad lucck"
elif [ $i == 7 ]
then 
echo "good luck"
else
echo "Best school"
fi 
((i++))
done
